services:
  app:
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: vision-api-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/actask-app-a125d7e12c21.json
      API_BASE_URL: http://127.0.0.1:8000
    volumes:
      - .:/app
      - ../front:/app/static:ro
      - ./credentials:/app/credentials:ro
    command: uvicorn main:app --host 0.0.0.0 --port 8000
